all:	StockTester1 StockTester2 StockTester3 

StockTester1:	Stock.h Stock.cpp StockTester1.cpp
	g++ -ggdb -o StockTester1 StockTester1.cpp Stock.cpp 

StockTester2:	Stock.h Stock.cpp StockTester2.cpp
	g++ -ggdb -o StockTester2 StockTester2.cpp Stock.cpp 

StockTester3:	Stock.h Stock.cpp StockTester3.cpp
	g++ -ggdb -o StockTester3 StockTester3.cpp Stock.cpp 

clean:
	rm StockTester1 StockTester2 StockTester3 
